# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalysis.proto\x12\x0burbanhealth\"+\n\x07Reading\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"_\n\x0f\x41nalysisRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x11\n\tdata_type\x18\x02 \x01(\t\x12&\n\x08readings\x18\x03 \x03(\x0b\x32\x14.urbanhealth.Reading\"\x9a\x01\n\x10\x41nalysisResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0csample_count\x18\x02 \x01(\x05\x12\x12\n\nmean_value\x18\x03 \x01(\x01\x12\x11\n\tmax_value\x18\x04 \x01(\x01\x12\x11\n\tmin_value\x18\x05 \x01(\x01\x12\x14\n\x0crisk_pattern\x18\x06 \x01(\t\x12\x0f\n\x07message\x18\x07 \x01(\t2]\n\x0f\x41nalysisService\x12J\n\x0b\x41nalyzeData\x12\x1c.urbanhealth.AnalysisRequest\x1a\x1d.urbanhealth.AnalysisResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READING']._serialized_start=31
  _globals['_READING']._serialized_end=74
  _globals['_ANALYSISREQUEST']._serialized_start=76
  _globals['_ANALYSISREQUEST']._serialized_end=171
  _globals['_ANALYSISRESPONSE']._serialized_start=174
  _globals['_ANALYSISRESPONSE']._serialized_end=328
  _globals['_ANALYSISSERVICE']._serialized_start=330
  _globals['_ANALYSISSERVICE']._serialized_end=423
# @@protoc_insertion_point(module_scope)
