networks:
  urban-net:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${PORT_RABBITMQ:-5672}:5672"
      - "${PORT_RABBITMQ_WEB:-15672}:15672"
    # O RabbitMQ usa nomes de variáveis diferentes, por isso mapeamos a partir do .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    networks:
      - urban-net
    
  python-preprocess:
    build:
      context: ./Services
      dockerfile: PreProcessing/Dockerfile
    container_name: python-preprocess
    env_file:
      - .env
    ports:
      - "${PORT_PYTHON_PRE:-50051}:50051"
    networks:
      - urban-net
    healthcheck:
      test: ["CMD", "python", "-c", "import grpc; stub = grpc.aio.secure_channel('localhost:50051', grpc.ssl_channel_credentials()).insecure_channel(); print('health')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  python-analysis:
    build:
      context: ./Services
      dockerfile: Analysis/Dockerfile
    container_name: python-analysis
    env_file:
      - .env
    ports:
      - "${PORT_PYTHON_ANALY:-50052}:50052"
    networks:
      - urban-net
    healthcheck:
      test: ["CMD", "python", "-c", "import grpc; stub = grpc.aio.secure_channel('localhost:50052', grpc.ssl_channel_credentials()).insecure_channel(); print('health')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  csharp-server: 
    build: 
      context: .
      dockerfile: Server/Dockerfile
    container_name: csharp-server
    env_file: 
      - .env
    ports: 
      - "${PORT_SERVER_TCP:-5001}:5001"
      - "${PORT_DASHBOARD:-8081}:8081"
    volumes:
      - "./database_data:/app/data"
    depends_on:
      - python-analysis
    networks:
      - urban-net
    
  csharp-gateway:
    build: 
      context: .
      dockerfile: Gateway/Dockerfile
    container_name: csharp-gateway
    env_file: 
      - .env
    volumes:
      - ./Gateway/Configs/gateway-config.json:/app/Configs/gateway_config.json
      - ./Gateway/Configs/sensors-config.json:/app/Configs/sensors_config.json
    depends_on:
      - rabbitmq
      - csharp-server
      - python-preprocess
    networks:
      - urban-net
    
  csharp-sensor:
    build:
      context: .
      dockerfile: Sensor/Dockerfile
    container_name: csharp-sensor
    env_file: 
      - .env
    volumes:
      - ./Sensor/Frames:/app/Frames
    stdin_open: true
    tty: true
    depends_on:
      - rabbitmq
    networks:
      - urban-net