networks:
  urban-broker:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${PORT_RABBITMQ:-5672}:5672"
      - "${PORT_RABBITMQ_WEB:-15672}:15672"
    env_file:
      - .env.distributed.broker
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE:-urbanhealth_secret_cookie}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 200s
    restart: unless-stopped
    networks:
      - urban-broker
  
