networks:
  urban-sensor:
    driver: bridge

services:
  csharp-sensor:
    build:
      context: .
      dockerfile: Sensor/Dockerfile
    container_name: csharp-sensor
    env_file:
      - .env.sensor.local
    ports:
      - "${PORT_SENSOR_UDP:-5002}:5002/udp"
    volumes:
      - ./Frames:/app/Frames
    stdin_open: true
    tty: true
    networks:
      - urban-sensor