networks:
  urban-sensor:
    driver: bridge

services:
  csharp-sensor:
    build:
      context: .
      dockerfile: Sensor/Dockerfile
    container_name: csharp-sensor
    env_file: 
      - .env.sensor
    volumes:
      - ./Frames:/app/Frames
    stdin_open: true
    tty: true
    networks:
      - urban-sensor